name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # https://yarnpkg.com/features/release-workflow/#ensuring-that-versions-are-bumped-ci
          fetch-depth: 0

      - name: Use specific Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build
